name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Backend
        run: |
          BACKEND_IMAGE=${{ secrets.DOCKER_USER }}/myapp-backend
          docker build -t $BACKEND_IMAGE:${{ github.run_number }} ./backend
          docker tag $BACKEND_IMAGE:${{ github.run_number }} $BACKEND_IMAGE:latest
          docker push $BACKEND_IMAGE:${{ github.run_number }}
          docker push $BACKEND_IMAGE:latest

      - name: Build Frontend
        run: |
          FRONTEND_IMAGE=${{ secrets.DOCKER_USER }}/myapp-frontend
          docker build -t $FRONTEND_IMAGE:${{ github.run_number }} ./frontend
          docker tag $FRONTEND_IMAGE:${{ github.run_number }} $FRONTEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:${{ github.run_number }}
          docker push $FRONTEND_IMAGE:latest
